### ISSUE TITLE
希望改进夜间模式，黑底白纸的夜间模式属实阴间。

### ISSUE THREAD

**Issue by mephisX** [liuyubing233/custom-zhihu#13]
![image](https://user-images.githubusercontent.com/30206556/143834248-4c01f44c-99e0-4aff-a165-012a4ff0340a.png)
GitHub 的夜间模式就很好。
背景：#181a1b
字体：#cecac3

**Comment by superPufferfish** [comment]
使用的知乎自带的夜间模式并在上面做了部分补充，后面抽时间把这块统一优化掉吧

**Comment by liuyubing233** [comment]
以改进...
