### ISSUE TITLE
希望添加的功能-首页推荐链接保存功能

### ISSUE THREAD

**Issue by AAws0sd** [liuyubing233/custom-zhihu#31]
作者大大可否出一个首页推荐的保存功能，默认保存几十个首页推荐的数据。
平时在工作中摸鱼的时候，会一直刷新知乎的首页看推荐的内容。有时候就手一划！不小心刷新或者关闭了，就再也找不到那条内容了:(
所以希望有一个地方可以临时保存一下，再出现这样的问题也就有地方可以回去查找了，感谢作者大大！

**Comment by KnIfER** [comment]
可以在右侧弄一个链接列表，显示所有展开过、点击/选择了文本的帖子

**Comment by liuyubing233** [comment]
添加了首页链接缓存功能
