### ISSUE TITLE
希望回答列表和知乎首页能使用不同的版心宽度。

### ISSUE THREAD

**Issue by KnIfER** [liuyubing233/custom-zhihu#37]

**Comment by KnIfER** [comment]
还有，点击“收起”的时候，希望可以保持页面横向滚动不变、保持高亮框

**Comment by KnIfER** [comment]
- [x] 保持高亮框
可通过点击List-Item追加classList样式解决，偶尔失效。

- [x] 改进悬浮按钮处理方式
直接检测固定的底部按钮栏`ContentItem-actions is-fixed`，缺点是页面放大为150%时，底部按钮栏始终不固定

**Comment by superPufferfish** [comment]
现在可以调整不同的版心了

**Comment by KnIfER** [comment]
li hai
