### ISSUE TITLE
关注列表怎么过滤自己啊，有点尴尬

### ISSUE THREAD

**Issue by KnIfER** [liuyubing233/custom-zhihu#53]
![image (4)](https://user-images.githubusercontent.com/11593903/217743462-5f5b5223-9b31-4ed4-8f78-8433664c877b.jpg)

**Comment by KnIfER** [comment]
希望可以单开一个作者名过滤之类的

**Comment by liuyubing233** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/33803840/228193991-a59e5a6d-5582-4dec-a6e3-0bbf04372b92.png">
最新版本添加了关注列表可以屏蔽自己的操作了
