### ISSUE TITLE
希望能增加回答操作文字隐藏后显示评论数量

### ISSUE THREAD

**Issue by huanghuanhuahuh** [liuyubing233/custom-zhihu#55]
基础设置-通用模块隐藏-回答操作文字
这个选项勾上后评论数量也会隐藏, 但有时候想知道回答的评论有没有对回答内容进行讨论
不知道作者大佬有没有计划新增显示评论数量的选项, 如果是我设置有疏忽先行道歉了

**Comment by liuyubing233** [comment]
添加了功能
<img width="496" alt="image" src="https://user-images.githubusercontent.com/33803840/230262567-48673ede-bcb9-4562-a818-e684697d84df.png">
<img width="358" alt="image" src="https://user-images.githubusercontent.com/33803840/230262636-c930c01e-37dd-4f77-837d-b893d4917385.png">
