### ISSUE TITLE
如何关闭快捷键唤起功能？

### ISSUE THREAD

**Issue by bcaso** [liuyubing233/custom-zhihu#57]
在写回答或文章时，输入 . 会唤起修改器。

**Comment by liuyubing233** [comment]
<img width="520" alt="image" src="https://github.com/liuyubing233/custom-zhihu/assets/33803840/b7447223-0c1a-4de2-be99-b9a29c146d37">
最新版本添加了关闭开启快捷键的功能，默认开启
