### ISSUE TITLE
左边距太小

### ISSUE THREAD

**Issue by BlueDolphin9527** [liuyubing233/custom-zhihu#58]
<img width="879" alt="左边距太小" src="https://github.com/liuyubing233/custom-zhihu/assets/62049321/ba52515c-dc25-45a8-9cf1-0b92bec053c1">
测试网址：https://www.zhihu.com/tardis/sogou/qus/26567824#CTZ_SET_BASIS
如图片中所看到的，左边距实在太小，而且整体UI不统一。

**Comment by liuyubing233** [comment]
添加了页面重定向，电脑端看手机端页面会重定向到电脑端了
