### ISSUE TITLE
似乎总会莫名其妙地自动弹出图片，点击空白处取消显示，又会自动跳出来，无法取消显示，刷新或许能解决问题，但无法杜绝。

### ISSUE THREAD

**Issue by FeiLZX3Km** [liuyubing233/custom-zhihu#62]
如题。
Microsoft Edge 版本 115.0.1901.200 (正式版本) (64 位)

**Comment by liuyubing233** [comment]
有没有其他插件冲突？是浏览回答还是问题的时候自动弹出图片？

**Comment by FeiLZX3Km** [comment]
> 有没有其他插件冲突？是浏览回答还是问题的时候自动弹出图片？

因为插件没有根据浏览器主题自动切换暗黑主题的功能，所以确实有安装其他两个知乎相关的脚本。但我想应该不是这两知乎脚本的原因导致图片冲突。至于其他脚本，也没有与图片相关的功能。所以我想可能并不是脚本冲突所致。
谈到插件的话，也没有与图片处理相关的插件。
相反，**图片功能我却知道本脚本有，那就是“使用弹窗打开动画”，问题可能还出现在此脚本上。**
什么时候弹出图片？**在首页浏览各种回答时或者打开某个问答页面时时都会出现此问题。**

**Comment by liuyubing233** [comment]
> > 有没有其他插件冲突？是浏览回答还是问题的时候自动弹出图片？
> 
> 因为插件没有根据浏览器主题自动切换暗黑主题的功能，所以确实有安装其他两个知乎相关的脚本。但我想应该不是这两知乎脚本的原因导致图片冲突。至于其他脚本，也没有与图片相关的功能。所以我想可能并不是脚本冲突所致。 谈到插件的话，也没有与图片处理相关的插件。 相反，**图片功能我却知道本脚本有，那就是“使用弹窗打开动画”，问题可能还出现在此脚本上。** 什么时候弹出图片？**在首页浏览各种回答时或者打开某个问答页面时都会出现此问题。**

可以把同时运行的脚本说一下，我去安装一下复原下这个情况。

**Comment by FeiLZX3Km** [comment]
> > > 有没有其他插件冲突？是浏览回答还是问题的时候自动弹出图片？
> > 
> > 
> > 因为插件没有根据浏览器主题自动切换暗黑主题的功能，所以确实有安装其他两个知乎相关的脚本。但我想应该不是这两知乎脚本的原因导致图片冲突。至于其他脚本，也没有与图片相关的功能。所以我想可能并不是脚本冲突所致。 谈到插件的话，也没有与图片处理相关的插件。 相反，**图片功能我却知道本脚本有，那就是“使用弹窗打开动画”，问题可能还出现在此脚本上。** 什么时候弹出图片？**在首页浏览各种回答时或者打开某个问答页面时都会出现此问题。**
> 
> 可以把同时运行的脚本说一下，我去安装一下复原下这个情况。

[屏蔽广告]屏蔽谷歌广告、百度广告、知乎广告、隐藏谷歌...
文本选中复制
屏蔽知乎营销号
去掉WEBP-转换WEBP圈片到源格式(JPG PNG GIF)用於Onen...
骚扰拦截
知乎修改器持续更新努力实现功能最全的知乎配置插件
字体渲染(自用脚本)
Ban Bad Websites 标记/屏蔽机器翻译 SEO 垃圾网站
Enhanced word highlight
RSS+: 显示当前网站所有的 RSS
搜索酱

这三个没有启用：
网页宽屏
知乎美化
知乎增强

**Comment by liuyubing233** [comment]
> > > > 有没有其他插件冲突？是浏览回答还是问题的时候自动弹出图片？
> > > 
> > > 
> > > 因为插件没有根据浏览器主题自动切换暗黑主题的功能，所以确实有安装其他两个知乎相关的脚本。但我想应该不是这两知乎脚本的原因导致图片冲突。至于其他脚本，也没有与图片相关的功能。所以我想可能并不是脚本冲突所致。 谈到插件的话，也没有与图片处理相关的插件。 相反，**图片功能我却知道本脚本有，那就是“使用弹窗打开动画”，问题可能还出现在此脚本上。** 什么时候弹出图片？**在首页浏览各种回答时或者打开某个问答页面时都会出现此问题。**
> > 
> > 
> > 可以把同时运行的脚本说一下，我去安装一下复原下这个情况。
> 
> [屏蔽广告]屏蔽谷歌广告、百度广告、知乎广告、隐藏谷歌... 文本选中复制 屏蔽知乎营销号 去掉WEBP-转换WEBP圈片到源格式(JPG PNG GIF)用於Onen... 骚扰拦截 知乎修改器持续更新努力实现功能最全的知乎配置插件 字体渲染(自用脚本) Ban Bad Websites 标记/屏蔽机器翻译 SEO 垃圾网站 Enhanced word highlight RSS+: 显示当前网站所有的 RSS 搜索酱
> 
> 这三个没有启用： 网页宽屏 知乎美化 知乎增强

version: 3.16.7
兼容「去掉WEBP - 转换WEBP图片到源格式(JPG PNG GIF)用于Onenote与Evernote剪藏」插件导致的动图一直弹窗的问题：
 这个插件会每秒都检测网页所有WEBP图片并进行转换，知乎网页的GIF图片均为WEBP，会导致在修改器插件中持续弹出弹窗的情况，已修复，
但是由于WEBP插件的修改，会导致弹窗打开动图后打开的动图会被替换为静态图片（没办法，我不能去修改其他插件的代码）。
所以建议在使用这个修改WEBP插件的时候关闭「使用弹窗打开动图」

**Comment by FeiLZX3Km** [comment]
> > > > > 有没有其他插件冲突？是浏览回答还是问题的时候自动弹出图片？
> > > > 
> > > > 
> > > > 因为插件没有根据浏览器主题自动切换暗黑主题的功能，所以确实有安装其他两个知乎相关的脚本。但我想应该不是这两知乎脚本的原因导致图片冲突。至于其他脚本，也没有与图片相关的功能。所以我想可能并不是脚本冲突所致。 谈到插件的话，也没有与图片处理相关的插件。 相反，**图片功能我却知道本脚本有，那就是“使用弹窗打开动画”，问题可能还出现在此脚本上。** 什么时候弹出图片？**在首页浏览各种回答时或者打开某个问答页面时都会出现此问题。**
> > > 
> > > 
> > > 可以把同时运行的脚本说一下，我去安装一下复原下这个情况。
> > 
> > 
> > [屏蔽广告]屏蔽谷歌广告、百度广告、知乎广告、隐藏谷歌... 文本选中复制 屏蔽知乎营销号 去掉WEBP-转换WEBP圈片到源格式(JPG PNG GIF)用於Onen... 骚扰拦截 知乎修改器持续更新努力实现功能最全的知乎配置插件 字体渲染(自用脚本) Ban Bad Websites 标记/屏蔽机器翻译 SEO 垃圾网站 Enhanced word highlight RSS+: 显示当前网站所有的 RSS 搜索酱
> > 这三个没有启用： 网页宽屏 知乎美化 知乎增强
> 
> version: 3.16.7 兼容「去掉WEBP - 转换WEBP图片到源格式(JPG PNG GIF)用于Onenote与Evernote剪藏」插件导致的动图一直弹窗的问题： 这个插件会每秒都检测网页所有WEBP图片并进行转换，知乎网页的GIF图片均为WEBP，会导致在修改器插件中持续弹出弹窗的情况，已修复， 但是由于WEBP插件的修改，会导致弹窗打开动图后打开的动图会被替换为静态图片（没办法，我不能去修改其他插件的代码）。 所以建议在使用这个修改WEBP插件的时候关闭「使用弹窗打开动图」

谢谢谢谢~辛苦了。
