### ISSUE TITLE
bug: 搜索时出现结果看不见，往下滑后出现别的且在跳动

### ISSUE THREAD

**Issue by Chun-J1** [liuyubing233/custom-zhihu#65]
正常搜索是这样
![Snipaste_2023-09-15_13-25-31](https://github.com/liuyubing233/custom-zhihu/assets/54700619/fccc4b96-1b44-4ec0-929a-71b4e73bf7fd)

有问题的是这样
![test](https://github.com/liuyubing233/custom-zhihu/assets/54700619/1fd70b84-25f0-477c-9495-d7d9b85835fe)

**Comment by Chun-J1** [comment]
这是我的配置：
{"hiddenAnswerRightFooter":true,"hiddenReadMoreText":true,"hiddenAD":true,"hiddenDetailFollow":true,"hidden618HongBao":true,"removeZhihuOfficial":false,"removeStoryAnswer":true,"removeYanxuanAnswer":true,"removeYanxuanRecommend":true,"removeYanxuanCPRecommend":true,"removeFromYanxuan":true,"removeUnrealAnswer":false,"removeFollowVoteAnswer":false,"removeFollowVoteArticle":false,"removeFollowFQuestion":false,"removeBlockUserContent":true,"removeBlockUserContentList":[],"removeItemAboutAD":false,"removeItemAboutArticle":false,"removeItemAboutVideo":false,"removeItemQuestionAsk":false,"removeLessVote":true,"lessVoteNumber":100,"removeLessVoteDetail":false,"lessVoteNumberDetail":100,"removeAnonymousAnswer":false,"removeMyOperateAtFollow":false,"suspensionHomeTab":true,"suspensionHomeTabPo":"left: 20px; top: 100px;","suspensionHomeTabFixed":true,"suspensionFind":false,"suspensionFindPo":"left: 10px; top: 380px;","suspensionFindFixed":true,"suspensionSearch":true,"suspensionSearchPo":"left: 10px; top: 400px;","suspensionSearchFixed":true,"suspensionUser":true,"suspensionUserPo":"right: 60px; top: 100px;","suspensionUserFixed":true,"suspensionPickUp":true,"customizeCss":"","answerOpen":"","filterKeywords":[],"showBlockUser":true,"versionHome":"831","versionAnswer":"1002","versionArticle":"703","zoomImageType":"2","zoomImageSize":"86","showGIFinDialog":true,"globalTitle":"","titleIco":"github","questionTitleTag":true,"listOutPutNotInterested":false,"fixedListItemMore":false,"highlightOriginal":true,"highlightListItem":false,"listItemCreatedAndModifiedTime":true,"answerItemCreatedAndModifiedTime":true,"questionCreatedAndModifiedTime":true,"articleCreateTimeToTop":true,"linkShopping":"0","linkAnswerVideo":"0","fontSizeForList":"13","fontSizeForAnswer":15,"fontSizeForArticle":16,"zoomListVideoType":"0","zoomListVideoSize":"500","hotKey":true,"theme":"1","themeLight":"0","themeDark":"3","colorText1":"#d8ddc6","colorBackground":"#272822","t":1694755772776,"hiddenLogo":true,"hiddenHeader":true,"hiddenHeaderScroll":false,"hiddenAppHeaderTabHome":false,"hiddenAppHeaderTabZhi":true,"hiddenAppHeaderTabVIP":true,"hiddenAppHeaderTabFind":true,"hiddenAppHeaderTabWaitingForYou":true,"hiddenAnswerText":true,"justVoteNum":false,"justCommitNum":false,"hiddenTopAD":false,"hiddenCommitReply":false,"hiddenHomeCreatorEntrance":true,"hiddenHomeRecommendFollow":true,"hiddenHomeCategory":true,"hiddenHomeCategoryMore":true,"hiddenHomeFooter":false,"hiddenHomeListTab":false,"hiddenHomeListTabFollow":false,"hiddenHomeListTabVideo":true,"hiddenHotItemIndex":false,"hiddenHotItemLabel":false,"hiddenHotItemMetrics":false,"hiddenAnswers":false,"hiddenListVideoContent":false,"hiddenItemActions":false,"hiddenListImg":true,"hiddenListAnswerInPerson":false,"hiddenFollowAction":false,"hiddenSearchBoxTopSearch":false,"hiddenSearchPageTopSearch":false,"hiddenSearchPageFooter":false,"hiddenFollowChooseUser":false,"hiddenZhuanlanTag":false,"hiddenZhuanlanVoters":false,"hiddenOpenButton":false}

**Comment by liuyubing233** [comment]
设置了屏蔽低赞内容，100赞以下的都被过滤掉了
![image](https://github.com/liuyubing233/custom-zhihu/assets/33803840/ac2de72d-309e-4591-bc0b-b67c72cc0047)

**Comment by Chun-J1** [comment]
> 设置了屏蔽低赞内容，100赞以下的都被过滤掉了 ![image](https://user-images.githubusercontent.com/33803840/268188745-ac2de72d-309e-4591-bc0b-b67c72cc0047.png)

不好意思，不知道啥时候自己开的，解决了
