### ISSUE TITLE
导出为PDF无法使用

### ISSUE THREAD

**Issue by Lowki097** [liuyubing233/custom-zhihu#66]
导出为PDF无法使用，点击后一直是 加载中...
鉴于现在很多回答收藏了也会随时消失，能不能考虑添加 在浏览回答的时候独立导出文章和评论 的功能。

Microsoft Edge
版本 117.0.2045.31 (正式版本) (64 位)
好用 希望越做越好

**Comment by liuyubing233** [comment]
请问是 windows 还是 mac？或者可不可以将导出的收藏夹提供一下。目前推测原因可能是图片资源太多导致加载速度缓慢

**Comment by Lowki097** [comment]
win10，好像不是图片太多的问题，测试其他图片更多的收藏夹可以正常导出。可能是单个回答过长或者单个图片太大。

**Comment by liuyubing233** [comment]
4.3.2版本导出PDF添加了进度显示，可以看看是不是资源太大卡住了，如果卡住了，按F12打开控制台查看network是哪一个资源卡住了
